#!/usr/local/bin/perl -s

use strict ;
use warnings ;
our $s ;

print "HELLO DEMO\n" ;

use File::Basename qw( basename );
$ENV{PATH} .= ':' . basename( $0 ) . ':./bin:.';
for my $prog qw( run_stem xterm ) {
    die "Can't find $prog in PATH\n" if
        system( "which $prog >/dev/null 2>&1" ) != 0;
}


$SIG{ 'INT' } = \&cleanup ;

my @children ;

my $ssfe = $s ? 'ssfe -prompt Stem:' : '' ;
my $echo = $s ? 'console_echo=1' : '' ;

my $cmd = <<CMD ;
xterm -T Hello -n Hello -geometry 80x40+0+0 -e $ssfe run_stem $echo hello
CMD

print "$cmd\n" ;

my @cmd = split ' ', $cmd ;
s/:/: / for @cmd ;

fork_exec( @cmd ) ;

1 while wait() != -1;

exit;



sub cleanup {

	print "clean up\n" ;

	kill 9, @children ;

	wait ;	
	exit ;

}

sub fork_exec {

	my( @exec ) = @_ ;

	if ( my $pid = fork() ) {

		push @children, $pid ;
		return ;
	}

	exec @exec ;
}
